#!/bin/sh
# grep for the important checks of an o-saft scan
# Usage:
#   1. o-saft +check --trace-key --header <my-host> > my-host.o-saft
#   2. o-saft-important-checks my-host.o-saft

grep -A 1000 "=== Performed Checks ===" $1 |grep --color=auto "[[:space:]]\+.*:[[:space:]]\+no"
